# Generated by Django 5.2 on 2025-06-19 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestionUtilisateurs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_formule", models.CharField(max_length=100)),
                (
                    "expression",
                    models.TextField(
                        help_text="Formule Python. Variables disponibles: jours_travailles, jours_ouvrables_annuels, jours_feries"
                    ),
                ),
                ("est_defaut", models.BooleanField(default=False)),
                ("publique", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-est_defaut", "nom_formule"],
            },
        ),
        migrations.CreateModel(
            name="Parametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=50, unique=True)),
                ("valeur", models.IntegerField()),
                ("est_const", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ReglesGlobaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jours_ouvrables", models.JSONField(default=list)),
                ("jours_feries", models.JSONField(default=list)),
                ("heure_debut_travail", models.TimeField(default="09:00")),
                ("heure_fin_travail", models.TimeField(default="17:00")),
                ("pause_midi_debut", models.TimeField(default="13:30")),
                ("pause_midi_fin", models.TimeField(default="14:00")),
                (
                    "pays_feries",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("payé", "Congé payé"),
                            ("spécial", "Spécial"),
                            ("sans_solde", "Sans solde"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("status", models.CharField(default="en attente", max_length=30)),
                ("commentaire", models.TextField(blank=True)),
                ("demi_jour", models.BooleanField(default=False)),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueSolde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_modif", models.DateField(auto_now_add=True)),
                ("solde_actuel", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegleCongé",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jours_ouvrables_annuels", models.IntegerField(default=230)),
                ("jours_acquis_annuels", models.IntegerField(default=18)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True, null=True)),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionUtilisateurs.equipe",
                    ),
                ),
                (
                    "formule_defaut",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestionCongesEtAbsences.formule",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("equipe", "manager")},
            },
        ),
        migrations.CreateModel(
            name="RegleMembrePersonnalisée",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("formule_personnalisee", models.TextField(blank=True)),
                ("jours_ouvrables_perso", models.IntegerField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                (
                    "membre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "regle_equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCongesEtAbsences.reglecongé",
                    ),
                ),
            ],
            options={
                "unique_together": {("regle_equipe", "membre")},
            },
        ),
    ]
