# Generated by Django 5.2 on 2025-06-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReglesGlobaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jours_ouvrables", models.JSONField(default=list)),
                ("heure_debut_travail", models.TimeField()),
                ("heure_fin_travail", models.TimeField()),
                ("pause_midi_debut", models.TimeField()),
                ("pause_midi_fin", models.TimeField()),
            ],
        ),
    ]
