# Generated by Django 5.2 on 2025-06-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCongesEtAbsences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglesglobaux",
            name="heure_debut_travail",
            field=models.TimeField(default="09:00"),
        ),
        migrations.AlterField(
            model_name="reglesglobaux",
            name="heure_fin_travail",
            field=models.TimeField(default="17:00"),
        ),
        migrations.AlterField(
            model_name="reglesglobaux",
            name="pause_midi_debut",
            field=models.TimeField(default="13:30"),
        ),
        migrations.AlterField(
            model_name="reglesglobaux",
            name="pause_midi_fin",
            field=models.TimeField(default="14:00"),
        ),
    ]
