# Generated by Django 5.2 on 2025-06-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCongesEtAbsences", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formule",
            options={"ordering": ["nom_formule"]},
        ),
        migrations.RemoveField(
            model_name="formule",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="formule",
            name="est_defaut",
        ),
        migrations.RemoveField(
            model_name="formule",
            name="expression",
        ),
        migrations.AddField(
            model_name="formule",
            name="expressions",
            field=models.TextField(
                default={"jours_acquis_annuels": "", "jours_ouvrables_annuels": ""},
                help_text="JSON avec les expressions, ex: {'jours_ouvrables_annuels': '...', 'jours_acquis_annuels': '...'}",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formule",
            name="nom_formule",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="formule",
            name="publique",
            field=models.BooleanField(default=True),
        ),
    ]
