# Generated by Django 5.2 on 2025-06-16 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionCongesEtAbsences",
            "0002_alter_reglesglobaux_heure_debut_travail_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_formule", models.CharField(max_length=100)),
                ("expression", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Parametre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=50, unique=True)),
                ("valeur", models.IntegerField()),
                ("est_const", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("payé", "Congé payé"),
                            ("spécial", "Spécial"),
                            ("sans_solde", "Sans solde"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("status", models.CharField(default="en attente", max_length=30)),
                ("commentaire", models.TextField(blank=True)),
                ("demi_jour", models.BooleanField(default=False)),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueSolde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_modif", models.DateField(auto_now_add=True)),
                ("solde_actuel", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegleDeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("nbr_max_jours_negatif", models.IntegerField(default=-10)),
                (
                    "formule_conge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionCongesEtAbsences.formule",
                    ),
                ),
                (
                    "formule_jours_ouvrable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regle_jours_ouvrable",
                        to="gestionCongesEtAbsences.formule",
                    ),
                ),
            ],
        ),
    ]
