# Generated by Django 5.2 on 2025-06-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionCongesEtAbsences",
            "0002_alter_formule_options_remove_formule_date_creation_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formule",
            name="expressions",
            field=models.JSONField(default=dict),
        ),
    ]
