# Generated by Django 5.2 on 2025-06-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionCongesEtAbsences",
            "0003_formule_parametre_demandeconge_historiquesolde_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reglesglobaux",
            name="jours_feries",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="reglesglobaux",
            name="pays_feries",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
