# Generated by Django 5.2 on 2025-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCongesEtAbsences", "0003_alter_formule_expressions"),
    ]

    operations = [
        migrations.AddField(
            model_name="formule",
            name="est_defaut",
            field=models.BooleanField(default=False),
        ),
    ]
