# Generated by Django 5.2 on 2025-06-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionCongesEtAbsences", "0004_formule_est_defaut"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglecongé",
            name="nbr_max_negatif",
            field=models.IntegerField(
                default=0,
                help_text="Nombre maximum de jours de congé pouvant être négatif",
            ),
        ),
        migrations.AlterField(
            model_name="reglecongé",
            name="jours_acquis_annuels",
            field=models.IntegerField(
                default=18, help_text="Nombre de jours de congé acquis par an"
            ),
        ),
        migrations.AlterField(
            model_name="reglecongé",
            name="jours_ouvrables_annuels",
            field=models.IntegerField(
                default=230,
                help_text="Calculé automatiquement si vide: (52 semaines * 5 jours) - 18 jours - jours fériés",
            ),
        ),
    ]
