# Generated by Django 5.2 on 2025-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="reset_token",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="reset_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
