# Generated by Django 5.2 on 2025-06-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_utilisateur_reset_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="first_login",
            field=models.BooleanField(default=True),
        ),
    ]
