# Generated by Django 5.2 on 2025-06-24 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestionUtilisateurs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_formation",
                    models.CharField(
                        choices=[
                            ("interne", "Formation Interne"),
                            ("externe", "Formation Externe"),
                            ("autoformation", "Autoformation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("intitule", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("heures", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "justificatif",
                    models.FileField(
                        blank=True, null=True, upload_to="formations/justificatifs/"
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifiant", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "taux_horaire",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("client", "Projet Client"),
                            ("interne", "Projet Interne"),
                            ("r&d", "Recherche et Développement"),
                        ],
                        default="interne",
                        max_length=20,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "equipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projets",
                        to="gestionUtilisateurs.equipe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImputationHoraire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heures", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("projet", "Heures productives (projets)"),
                            ("formation", "Formation"),
                            ("absence", "Absence"),
                            ("autre", "Autre activité"),
                        ],
                        default="projet",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("valide", models.BooleanField(default=False)),
                ("date_saisie", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imputations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imputations",
                        to="gestionImputations.projet",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employe"],
                "unique_together": {("employe", "projet", "date")},
            },
        ),
        migrations.CreateModel(
            name="SemaineImputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semaine", models.IntegerField()),
                ("annee", models.IntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("soumis", "Soumis pour validation"),
                            ("valide", "Validé"),
                            ("rejete", "Rejeté"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_soumission", models.DateTimeField(blank=True, null=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("commentaire", models.TextField(blank=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semaines_imputation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-annee", "-semaine"],
                "unique_together": {("employe", "semaine", "annee")},
            },
        ),
    ]
