# Generated by Django 5.2 on 2025-06-28 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionImputations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="identifiant",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=50, unique=True
            ),
        ),
    ]
