# Generated by Django 5.2 on 2025-06-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionImputations", "0002_alter_projet_identifiant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imputationhoraire",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="imputations",
                to="gestionImputations.projet",
            ),
        ),
    ]
