# Generated by Django 5.2 on 2025-07-01 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionImputations", "0003_alter_imputationhoraire_projet"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="imputationhoraire",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="imputationhoraire",
            constraint=models.UniqueConstraint(
                fields=("employe", "projet", "date", "heures", "description"),
                name="uniq_imputation_exacte",
            ),
        ),
    ]
