# Generated by Django 5.2 on 2025-07-02 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestionImputations", "0004_alter_imputationhoraire_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="imputationhoraire",
            name="uniq_imputation_exacte",
        ),
        migrations.AddField(
            model_name="imputationhoraire",
            name="formation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imputations",
                to="gestionImputations.formation",
            ),
        ),
        migrations.AddConstraint(
            model_name="imputationhoraire",
            constraint=models.UniqueConstraint(
                condition=models.Q(("categorie", "projet")),
                fields=("employe", "date", "projet", "heures", "description"),
                name="uniq_imputation_projet",
            ),
        ),
        migrations.AddConstraint(
            model_name="imputationhoraire",
            constraint=models.UniqueConstraint(
                condition=models.Q(("categorie", "formation")),
                fields=("employe", "date", "formation", "heures", "description"),
                name="uniq_imputation_formation",
            ),
        ),
    ]
