# Generated by Django 5.2 on 2025-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gestionImputations",
            "0005_remove_imputationhoraire_uniq_imputation_exacte_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="imputationhoraire",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("projet", "Heures productives (projets)"),
                    ("formation", "Formation"),
                    ("absence", "Absence"),
                    ("reunion", "Réunion"),
                    ("admin", "Tâche administrative"),
                    ("autre", "Autre activité"),
                ],
                default="projet",
                max_length=20,
            ),
        ),
    ]
